version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: YourStrongPassword
    ports:
      - 3306:3306

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: YourStrongPassword
    ports:
      - 3307:3306

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: YourStrongPassword
    ports:
      - 5432:5432

  informix:
    platform: linux/x86_64
    image: icr.io/informix/informix-developer-database
    ports:
      - 9088:9088
      - 9089:9089

  memcached:
    image: memcached
    ports:
      - 11211:11211

  mssql:
    platform: linux/x86_64
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: DevCharlie4
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S . -U sa -P DevCharlie4"]
      interval: 1s
      timeout: 5s
      retries: 120
    restart: always
  
  # flyway:
  #   image: flyway/flyway
  #   command: migrate -url="jdbc:sqlserver://db;databaseName=master;encrypt=false;trustServerCertificate=true" -user="sa" -password="DevCharlie4" -mixed=true -placeholders.database_user_password="Test2Alpha212!" -placeholders.asymmetric_password="Test2Alpha1234!" -placeholders.master_key_password="U#IEVx95zX7nXhKvJn6"
  #   volumes:
  #     - ./sql:/flyway/sql
  #   depends_on:
  #     db:
  #       condition: service_healthy

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u root -p example --quiet | grep 1
      interval: 5s
      timeout: 3s
      retries: 30
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: encryption

  redis:
    image: redis:latest
    command: redis-server
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=Romeo1Sierra@Zulu
      - REDIS_AOF_ENABLED=no
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 30
      
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - cassandra:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  # cassandra-load-keyspace:
  #   container_name: cassandra-load-keyspace
  #   image: cassandra:latest
  #   depends_on:
  #     cassandra:
  #       condition: service_healthy
  #   volumes:
  #     - ./ai_data_injector/DataSchema/Cassandra_Schema.cql:/schema.cql
  #   command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"